apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "todo-chatbot.fullname" . }}-config
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "todo-chatbot.labels" . | nindent 4 }}
data:
  next_public_api_url: {{ .Values.env.nextPublicApiUrl | quote }}
  next_public_better_auth_url: {{ .Values.env.nextPublicBetterAuthUrl | quote }}